### ISSUE TITLE
Wrong mesh_shape

### ISSUE THREAD

**Issue by StrangeTcy** [EleutherAI/gpt-neo#119]
Trying out the notebook on colab TPUs with both `"mesh_shape":"x:4,y:2"` and ` "mesh_shape":"all:8"`  led to the following error:
```
Traceback (most recent call last):
  File "main.py", line 256, in <module>
    main(args)
  File "main.py", line 230, in main
    estimator.train(input_fn=partial(input_fn, global_step=current_step, eval=False), max_steps=next_checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3130, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3125, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2962, in _call_model_fn
    config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3242, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1484, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1547, in _invoke_input_fn_and_record_structure
    enqueue_ops.append(wrap_fn(device=host_device, op_fn=enqueue_ops_fn))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3771, in _wrap_computation_in_while_loop
    parallel_iterations=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2774, in while_loop
    return_same_structure)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2256, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2181, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3760, in computation
    with tf.control_dependencies(op_fn()):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1217, in enqueue_ops_fn
    placement_function=device_function_impl)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/tpu_feed.py", line 631, in generate_enqueue_ops
    for (shard, index) in zip(sharded_inputs, xrange(self.number_of_shards))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/tpu_feed.py", line 631, in <listcomp>
    for (shard, index) in zip(sharded_inputs, xrange(self.number_of_shards))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1162, in tpu_ordinal_function_impl
    if ctx.device_assignment:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 420, in device_assignment
    if self._model_parallelism_enabled else None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 353, in _get_device_assignment
    num_replicas=self.num_replicas)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/device_assignment.py", line 374, in device_assignment
    topology = Topology(serialized=topology)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/topology.py", line 80, in __init__
    self._parse_topology(serialized)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/topology.py", line 111, in _parse_topology
    "entries; got {}".format(self._mesh_shape))
ValueError: `mesh_shape` must be a vector of size 4 with positive entries; got [2 2 2]
```

ETA: running a `sudo apt update && sudo apt -y upgrade` solved the problem. But I guess is has something to do with versions of tensorflow and mesh-tensorflow.

**Comment by StrangeTcy** [comment]
Apparently installing `tensorflow==1.1.5.2` also solves this, but leads to [CrossShardOptimizer problems](https://github.com/EleutherAI/gpt-neo/issues/120)

**Comment by StellaAthena** [comment]
> Apparently installing `tensorflow==1.1.5.2` also solves this, but leads to [CrossShardOptimizer problems](https://github.com/EleutherAI/gpt-neo/issues/120)

To clarify, the original issue appears in TF 2.x?

**Comment by StrangeTcy** [comment]
> > Apparently installing `tensorflow==1.1.5.2` also solves this, but leads to [CrossShardOptimizer problems](https://github.com/EleutherAI/gpt-neo/issues/120)
> 
> To clarify, the original issue appears in TF 2.x?

Yes, unless I'm misremembering.

**Comment by StellaAthena** [comment]
Hi! Thanks for the feedback. We pushed some updates including a totally revamped notebook, give it a try and let me know if you're still getting this error.
