### ISSUE TITLE
ValueError in data/create_tfrecords.py after unzip openwebtext.tar.xz

### ISSUE THREAD

**Issue by MulinT-UN** [EleutherAI/gpt-neo#132]
Hi,

I'm trying to follow the GPTNeo_example_notebook. After `tar xf openwebtext.tar.xz` and `python3 data/create_tfrecords.py --mode documents --input_dir /content/GPTNeo/openwebtext --name openwebtext --output_dir openwebtext_tokenized --write_dataset_config`, I encountered ValueError

> 2021-02-09 08:57:16.075990: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-09 08:57:16.076052: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "data/create_tfrecords.py", line 205, in <module>
    results = create_tfrecords_mp(files, args)
  File "data/create_tfrecords.py", line 186, in create_tfrecords_mp
    files = split_list(files, len(files) // args.processes)
  File "data/create_tfrecords.py", line 67, in split_list
    return [l[i:i+n] for i in range(0, len(l), n)]
ValueError: range() arg 3 must not be zero

Any help will be appreciated!

**Comment by StellaAthena** [comment]
What is `n` when this code executes?

**Comment by MulinT-UN** [comment]
Sorry. Typo in input_dir arg!
