### ISSUE TITLE
Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

### ISSUE THREAD

**Issue by c-box** [EleutherAI/gpt-neo#160]
**Describe the bug**
```
Traceback (most recent call last):
  File "main.py", line 258, in <module>
    main(args)
  File "main.py", line 96, in main
    save_config(params, params["model_path"])
  File "/data/cbox/source_code/GPTNeo/utils.py", line 122, in save_config
    summary_writer = tf.summary.FileWriter(f"{logdir}/config", sess.graph)
  File "/data/cbox/anaconda3/envs/gptneo/lib/python3.7/site-packages/tensorflow/python/summary/writer/writer.py", line 368, in __init__
    filename_suffix)
  File "/data/cbox/anaconda3/envs/gptneo/lib/python3.7/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 71, in __init__
    gfile.MakeDirs(self._logdir)
  File "/data/cbox/anaconda3/envs/gptneo/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 468, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "/data/cbox/anaconda3/envs/gptneo/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 483, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 401 with body '{
  "error": {
    "code": 401,
    "message": "Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.",
    "errors": [
      {
        "message": "Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.",
        "domain": "global",
        "reason": "required",
        "locationType": "header",
        "location": "Authorization"
      }
    ]
  }
}
'
	 when reading metadata of gs://neo-d/models/GPT3_XL_Pile/config
```

**To Reproduce**
I downloaded the Pretrained model (1.3B version) and tried to make a simple inference using the script:
```
python3 main.py --predict --prompt <example_prompt.txt> --gpu_ids <device:GPU:0 device:GPU:1> --model <config_name>
```

**Environment (please complete the following information):**
 - GPUs: NVIDIA TITAN RTX
 - CUDA version: 11.0 
 - OS: Ubuntu 16.04

**Comment by StellaAthena** [comment]
Is your Google Cloud Bucket set up to allow remote access over HTTP? That's a setting that you may have to enable or may have disabled in the past.

**Comment by c-box** [comment]
> Is your Google Cloud Bucket set up to allow remote access over HTTP? That's a setting that you may have to enable or may have disabled in the past.

Thanks, I'll modify the model path to local instead of Google Cloud Bucket.
