### ISSUE TITLE
ValueError: Unrecognized configuration class <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoConfig'> 

### ISSUE THREAD

**Issue by dPacc** [EleutherAI/gpt-neo#204]
I'm trying to set up GPT-Neo on my local machine. I am getting the following error when I run the following commands

```
from transformers import pipeline
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')
```

ERROR: -

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpacman/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 371, in pipeline
    framework, model = infer_framework_from_model(model, targeted_task, revision=revision, task=task)
  File "/home/dpacman/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/transformers/pipelines/base.py", line 90, in infer_framework_from_model
    model = model_class.from_pretrained(model, **model_kwargs)
  File "/home/dpacman/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 382, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoConfig'> for this kind of AutoModel: TFAutoModelForCausalLM.
Model type should be one of BertConfig, OpenAIGPTConfig, GPT2Config, TransfoXLConfig, XLNetConfig, XLMConfig, CTRLConfig.
```

**Comment by StellaAthena** [comment]
You need to update to the newest version of `transformers`. If you have trouble doing so, please post on the `transformers` repository instead of here.

**Comment by Spooksan** [comment]
I am using the latest version of the transformer library and still getting the same error.

**Comment by StellaAthena** [comment]
ValueError: Unrecognized configuration class <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoConfig'> for this kind of AutoModel: **TFAutoModelForCausalLM.**



![Capture](https://user-images.githubusercontent.com/15899312/114563870-cfe8a300-9c3d-11eb-8b20-ef4ba7abfefe.PNG)
